rust-lang/sync-team

- Cargo.lock
- Cargo.toml
- README.md
- src/github/api.rs
- src/mailgun/mod.rs
- src/main.rs
This is a followup to https://github.com/rust-lang/team/pull/515.
r? @Mark-Simulacrum
> Add support for encrypted email addresses

- Cargo.lock
- Cargo.toml
- src/github/api.rs
- src/github/mod.rs
- src/mailgun/api.rs
- src/mailgun/mod.rs
- src/main.rs
- src/team_api.rs
- src/zulip/api.rs
- src/zulip/mod.rs
`failure` is no longer maintained.
> Switch from failure to anyhow

- src/github/mod.rs
For now only delete teams that are in the rust-lang org
> Don't delete teams in other orgs

- src/github/api.rs
> Fix bad url

- Cargo.lock
- src/github/api.rs
- src/github/mod.rs
- src/team_api.rs
This fixes an issue currently in production.
> Repo descriptions are optional

- README.md
The sync-team tool now does more than it used to.
> Update readme to reflect what sync-team does with GitHub

- src/github/api.rs
This fixes json deserialization errors.
> Don't deserialize unit

- src/github/api.rs
We were not sending the request body.
> Fix updating branch protection

- src/github/mod.rs
Since #16 we now diff the team repo definitions with GitHub and then apply the diff so `syncronize_teams` is now redundant and can be removed.
> Remove syncing teams since we now do diff/apply

- Cargo.lock
This fixes the reason CI is currently broken.
> Update ssl crate

- src/github/api.rs
- src/github/mod.rs
- src/mailgun/api.rs
- src/zulip/api.rs
> If branch restrictions are empty, serialize them as null

- Cargo.toml
- src/github/api.rs
- src/github/mod.rs
- src/mailgun/api.rs
- src/mailgun/mod.rs
- src/main.rs
- src/team_api.rs
- src/zulip/api.rs
- src/zulip/mod.rs
CI is failing due to these issues.
> Fix clippy issues

- Cargo.lock
- src/github/mod.rs
Based on changes in team repo: https://github.com/rust-lang/team/pull/938
> Update team_data dependency

- src/github/api.rs
More issues:
> error decoding response body: invalid type: map, expected unit at line 1 column 8
> Another wrong graphql type

- src/github/api.rs
`pushActorIds` indicates who is allowed to bypass push restrictions (a.k.a. merge restrictions). When bors is set as a bot we interpret that to mean "restrict merging to only bors - members with write permissions can no longer merge PRs". So, when bors is set as a bot, we set "pushActorIds" to bors' user id. 
We were correctly sending this "pushActorIds" array to GitHub in the mutation, but we did not set "restrictsPushes" to true which caused the "pushActorIds" to just be ignored. Now, we check if "pushActorIds" is empty and if not, we set "restrictsPushes" to true.
> Set the restrictPushes flag when pushActorIds is not empty

- src/github/api.rs
- src/github/mod.rs
Fixes #42 (with the exception of the "nice-to-have" feature of detecting stale invites).
Some users have not yet accepted the invite to join a specific team - if this is the case, we check for that and don't try to invite them again.
> Check invites to see if member has been added but not accepted

- src/github/api.rs
We should allow 404s on DELETEs because presumably the resource was already deleted. We'll need to be extra careful to not introduce a bug where the URL is malformed though.
> Allow DELETEs to return 404

- src/main.rs
Not much to say about this :sweat_smile:
> Update usage instructions

- src/github/mod.rs
- src/main.rs
Open to feedback on the implementation - not sure this is the best place. I hope it's sufficient.
> Fix security team

- src/github/api.rs
Small improvements to hopefully debug current sync failures.
> Improve errors

- src/main.rs
- src/zulip/mod.rs
This continues the work of moving to a diff then apply model for team sync started in #16.
> Move to a diff model for Zulip as well

- Cargo.lock
- Cargo.toml
- src/github/api/mod.rs
- src/github/api/read.rs
- src/github/api/write.rs
- src/github/mod.rs
- src/github/tests/mod.rs
- src/github/tests/test_utils.rs
- src/main.rs
This PR contains some basic infrastructure for testing the diffs (and later also GitHub API calls) generated by `sync-team`.
> Add testing infrastructure

- Cargo.lock
- src/github/api/mod.rs
- src/github/api/read.rs
- src/github/mod.rs
- src/github/tests/test_utils.rs
- src/mailgun/api.rs
- src/mailgun/mod.rs
- src/zulip/api.rs
- src/zulip/mod.rs
Usize wasn't really a good fit.
> Switch usize datatype to u64

- src/github/mod.rs
This was causing sync-team to not build and deploy.
> Fix clippy error

- Cargo.lock
- src/github/api/mod.rs
- src/github/api/write.rs
- src/github/mod.rs
- src/github/tests/test_utils.rs
Implements the sync logic for https://github.com/rust-lang/team/pull/1359.
> Implement sync of "PR required" property

- src/github/api/mod.rs
- src/github/mod.rs
- src/github/tests/mod.rs
- src/github/tests/test_utils.rs
Adds more tests, this time for repositories.
> Add tests for repo management

- src/zulip/api.rs
trying to investigate https://github.com/rust-lang/sync-team/pull/92#issuecomment-2713731866 better
> improve stream membership error message

- src/zulip/api.rs
hopefully fix for https://github.com/rust-lang/sync-team/pull/110#issuecomment-2713832523
> fix stream membership form

- src/github/api/mod.rs
- src/github/api/read.rs
- src/github/api/tokens.rs
- src/github/api/url.rs
- src/github/api/write.rs
> parse github tokens at program start

- src/github/mod.rs
- src/main.rs
- src/zulip/mod.rs
these lines don't look nice in the logs imo
> don't print diffs if empty

- src/zulip/api.rs
- src/zulip/mod.rs
closes https://github.com/rust-lang/sync-team/issues/116
> add rustlang-owner to private streams

- src/github/api/read.rs
Related to #121 
As you can see from the dry run, `Enable auto-merge` is no longer in the diff
> convert github repo rest api call to graphql

- .github/workflows/dry-run.yml
this should speed up the dry run because `cargo run` should be faster.
> add rust cache to dry run

- src/zulip/api.rs
Should fix https://github.com/rust-lang/sync-team/pull/111#issuecomment-2733827618.
Changed according to https://zulip.com/api/subscribe#parameters.
> Fix Zulip API request
