rust-lang/sync-team

Cargo.lock, src/github/api.rs, src/github/mod.rs, src/team_api.rs
This follows up on https://github.com/rust-lang/team/pull/801 by syncing repo information encoded in the team repo with GitHub.
The data that is synced is:
* Repo name/org
* Repo description
* Teams and their permissions
* Bots and their permissions
Given the configuration for the [team repo as it is encoded in the team repo](https://github.com/rust-lang/team/blob/44bf784ea04e2a8d75f0b558c86b64da95484f66/repos/team.toml), the following would change:
currently the team repo has the [bots team](https://github.com/orgs/rust-lang/teams/bots) as a team on the repo. This change would add each individual bot to the repo. 
We could change the encoding in the team repo to allow specifying that a repo should have all bots, but perhaps these bots aren't actually necessary?
Lastly, I haven't actually …
=> Sync Repos

Cargo.lock, src/github/api.rs, src/github/mod.rs
This builds off of https://github.com/rust-lang/team/pull/804 and syncs the definitions with GitHub.
This change is good enough to recreate the permissions on the team repo with one exception: the team repo currently dismisses stale reviews, but this sets the repo to not dismiss stale reviews. @Mark-Simulacrum was of the opinion that we should default to not dismissing stale reviews. This seems like a reasonable default, but I would argue it definitely does not make sense for the team repo as we want to ensure that every change has been reviewed carefully (after all - permissions are at stake).
=> Sync branch protection

src/github/api.rs, src/github/mod.rs
When creating a repo, we also attempt to create missing branches so that we can add branch protections. This does not work for brand new repos where the default branch has no commits in it as branches need to have some commit in order to be created.
This changes it so that the branches only get created if there is a main branch commit. This means that until someone pushes a main branch commit, none of the branch protections will be created. 
@Mark-Simulacrum this also speaks to potentially wanting to run this code more often so that things become consistent more quickly.
=> Do not create branch when there is no default branch commits

.github/workflows/ci.yml
Merging needs to be sync'd with deploying terraform changes (could be avoided with a multi-step deployment but doesn't seem worth it).
=> Move to OIDC authentication for ECR deployment

Cargo.lock, src/github/api.rs, src/github/mod.rs
Fixes a bug where we were not syncing these permissions (which is currently blocking sync-team from running).
=> Sync triage permissions

Cargo.lock, src/github/api.rs, src/github/mod.rs
When bors is listed as a bot, give bors push access to protected branches.
=> Allow bors push access if listed as a bot

.github/workflows/ci.yml
Following up on rust-lang/simpleinfra#128, this kicks off the start-sync-team lambda function when any PR is merged.
=> Invoke the start-sync-team lambda function on merge

src/github/mod.rs
For repos that use bors, it's not necessary to require a GitHub approval before merging (bors ensures that the PR is properly reviewed).
=> Only require approval when not using bors

src/github/api.rs, src/github/mod.rs
Now that all teams are managed from the team repo, we can also delete ones that are not referenced by the team repo. This ensures everything stays tidy.
=> Delete GitHub teams that are not referenced in team repo

Cargo.lock, src/github/api.rs, src/github/mod.rs
https://github.com/rust-lang/team/pull/875 adds information on individual repository collaborators. This sync that information with GitHub.
=> Sync individual repo collaborators

src/github/api.rs, src/github/mod.rs
This might be easiest to review commit by commit. This PR does not change functionality. Instead it's largely a cosmetic change.
I hope to next move this code to the team repo where we will have a single GitHub client that both the team repo and sync-team can rely on.
=> Cleanup GitHub Client

src/github/mod.rs
=> Allow sync-team to delete stale teams in the rust-lang-nursery org

.github/workflows/run.yml
Allows the running of the team-sync tool on demand which can be useful when investigating potentially spurious failures.
=> Run team sync tool on demand from CI

src/github/api.rs
If we get a 404 that means the team already doesn't exist so there's no need to fail.
=> Don't fail on 404 for delete team

src/github/api.rs, src/github/mod.rs
This fixes two issues currently breaking the sync mechanism:
* Some older repo member permissions come back as "pull" instead of "read". We now handle this.
* Freshly created repos don't have main branches so we could not create branch protections. We now handle the missing branch gracefully and also auto init the repo so that it should always have an initial commit. 
~CI is failing due to #35~
=> Handle missing main branch for branch protections

src/github/api.rs, src/github/mod.rs
Based on the changes from #34. Needed to support rust-lang/team#937.
The current version of sync-team deals in protected *branches* rather than *branch protection rules*. This means that if a repo config configures a protected branch name `rust-1.*`, the sync tool will look for a branch called exactly `rust-1.*` and attempt to create or update the rule that protects that branch.
This approach is obviously wrong as we want to think in terms of protection rules that can potentially span past a single branch just like Cargo currently does today. 
One small reason I originally went down this route is that the REST API does not support querying for or creating branch protection rules (only getting and manipulating branch protections rules for a single given branch). However, the [graphql API …
=> Rethink branch protection handling

src/github/api.rs
Fixes the following error message:
> caused by: graphql error: bool isn't a defined input type (on $dismissStale)
=> Use correct graphql input types

src/github/api.rs
Fixes the error:
> Type mismatch on variable $id and argument branchProtectionRuleId (String! / ID!)
=> Fix another wrong type

src/zulip/api.rs, src/zulip/mod.rs
We were getting errors because we expected emails to always be present which may no longer be the case.
=> Zulip users may now hide their emails from admins

src/github/api.rs, src/github/mod.rs
If someone sets a team as a push allowance actor, don't error.
This does not yet allow setting a team in the repo config toml. That will be done in a follow up.
=> Gracefully handle when a team is a push allowance actor

src/github/api.rs, src/main.rs, src/team_api.rs, src/utils.rs
Should help with debugging deserialization errors.
=> Log type that has failed to deserialize itself from a request

src/github/api.rs, src/github/mod.rs
When a team does not have a description, GitHub's API sets the `description` field to `null`. This breaks deserialization, which expects the field to be set to a `String`.
This is most likely only an issue for teams that have not previously been managed by sync-team, e.g. when an existing organizations is added to the team repository.
=> Team descriptions can be null

src/github/api.rs
While working on `sync-team`, I noticed that the diff always contained the same change (both locally and in production):
```
Team Diffs:
💻 Repo Diffs:
📝 Editing repo 'rust-lang/libc':
Branch Protections:
main
Allowances: [] => [User(UserPushAllowanceActor { login: "bors" })]
📝 Editing repo 'rust-lang/project-stable-mir':
Branch Protections:
main
Allowances: [] => [User(UserPushAllowanceActor { login: "bors" })]
```
Checking the implementation, it seems that we have a bug in our code that _disables_ restrictions when we have defined a push actor, which means the actor is never set by GitHub.
=> Fix restricting pushes to bots

Cargo.lock, Cargo.toml, src/github/api.rs, src/github/mod.rs
Synchronization part of https://github.com/rust-lang/team/pull/1164.
r? @Mark-Simulacrum
=> Add support for syncing branch protection required approval count

src/github/api/mod.rs, src/main.rs
This reverts commit 357f2c7ab1e9edfd057d71b582fa4dc5159b681b.
The check was too strict, since it didn't allow GraphQL requests that use POST for read-only actions. Let's just disable the check for now.
=> Revert "Add read-only flag to `HttpClient`"

src/github/api/mod.rs
It seems we forgot to add the headers to the client builder.
=> Actually add default headers for GitHub client

Cargo.lock, src/github/api/mod.rs, src/github/api/write.rs, src/github/mod.rs, src/github/tests/test_utils.rs, src/main.rs
`team` part of this change: https://github.com/rust-lang/team/pull/1282
=> Read branch protection push allowances from `rust_team_data`

src/mailgun/mod.rs
A recent release of nightly has started warning about redundant imports. This removes that warning.
=> Remove redundant imports.

Cargo.lock, src/github/api/mod.rs, src/github/api/write.rs, src/github/mod.rs
This adds syncing of the `homepage` repository setting added in https://github.com/rust-lang/team/pull/1353.
I decided to collect repository settings into a single struct with the expectation that we might add more settings in the future.
=> Sync the Repository homepage setting.

Cargo.lock, src/github/api/mod.rs, src/github/api/write.rs, src/github/mod.rs
Implements repository (un)archiving, based on https://github.com/rust-lang/team/pull/1165. If no archiving change was made, the `archived` attribute won't even be sent to GitHub.
=> Implement repository archiving and unarchiving

Cargo.lock, src/github/api/mod.rs, src/github/api/write.rs, src/github/mod.rs
`sync-team` part of https://github.com/rust-lang/team/pull/1377. Also did some refactoring of repo settings, since it was becoming cumbersome to pass around a bunch of independent variables around.
=> Set `allow_auto_merge` on repositories

src/github/api/mod.rs, src/github/api/write.rs, src/github/mod.rs
1) Archived repositories might not return non-required attributes, which `allow_auto_merge` is.
2) Archived repositories should not be modified.
~The `unwrap_or(false)` part isn't ideal, but in this case we simply cannot query the GH state, so there's probably no way to calculate the real diff. In theory, this could cause us to miss auto-enabling auto merge for a repository that is being unarchived, during the first sync, but it should be resolved on the following sync.~ Actually, it should be fine, as the diff won't be missed, since we are unarchiving in the first place, so there is some diff.
=> Fix `allow_auto_merge` in combination with repository archiving

Cargo.lock, src/github/api/mod.rs, src/github/api/read.rs, src/github/api/write.rs, src/github/mod.rs, src/github/tests/test_utils.rs
This PR implements addition and removal of repositories to GitHub app installations. Supported apps are specific variants of the `v1::Repo::Bot` enum, the first supported app is `RenovateBot`. To add a new app, it just needs to be added to the enum in `team` and also here, with its app ID.
**Needs https://github.com/rust-lang/team/pull/1410 to be merged first!**
=> Synchronize GitHub app installation

src/github/mod.rs
This should making look at diffs easier.
=> Clean up logs by not showing headers on empty diffs

.github/workflows/ci.yml, rust-toolchain.toml
To avoid surprises with e.g. new Clippy errors breaking CI.
=> CI: pin Rust version

Cargo.lock, Cargo.toml, src/github/api/mod.rs
Updating the dependencies only required a small change with regard to the base64 crate.
Everything seems to compile fine, doing `cargo run` errors with a 404 however but this also seems to happen for me on `master`. 
It might also be nice to switch `reqwest` over from OpenSSL to the RusTLS, just so it doesn't require openssl to be installed to build. But didn't want to just lump it in without asking.
Finally, we still depend on `hyper_old_types` because we're using the typed headers for `Link`. Unfortunately these have not been added to `headers` yet: https://github.com/hyperium/headers/pull/67, https://github.com/hyperium/headers/pull/113. I think it's fine like this for now, but we should probably switch when those do land.
Fixes #87
=> chore: update dependencies

Cargo.lock, Cargo.toml
As discussed in #89:
> It might also be nice to switch reqwest over from OpenSSL to the RusTLS, just so it doesn't require openssl to be installed to build.
As I had to disable the default features, I enabled the non-openssl ones again. 
Everything seems to work fine.
=> switch to rustls

src/github/api/write.rs
Documented [here](https://docs.github.com/en/graphql/reference/input-objects#createbranchprotectionruleinput).
Discussion: https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/enforced.20branch.20updates.20on.20the.20blog.20repo
=> Disable "Require branches to be up-to-date" for branch protections

Cargo.lock, src/github/mod.rs
This PR improves compatibility of `sync-team` with the new bors, by configuring bors permissions per branch (https://github.com/rust-lang/team/pull/1576), and also by teaching `sync-team` about the Rust bors GitHub app. This means that using `bots = ["bors"]` in `team` will now install the new bors to that repo.
This should be a no-op now, as there is currently no repo using bors/homu in `team`.
You can double-check the app ID at https://github.com/organizations/rust-lang/settings/apps/rust-bors.
=> Improve compatibility with new bors

src/github/api/read.rs, src/github/mod.rs, src/github/tests/mod.rs, src/github/tests/test_utils.rs
Re-adds branch protection test logic that was originally included in https://github.com/rust-lang/sync-team/pull/65.
=> Add branch protection tests

.github/workflows/dry-run.yml
To avoid angry e-mails from GitHub on forks :)
=> Only run the dry-run workflow in the rust-lang organization

.github/workflows/dry-run.yml
We removed this org from the `team` repo in https://github.com/rust-lang/team/pull/1652
=> remove unused conduit token from dry-run workflow

src/github/api/read.rs, src/github/mod.rs, src/github/tests/mod.rs
To avoid spurious diffs, as it seems that the ordering is not necessarily kept by GitHub.
This should fix one spurious diff from production:
```
📝 Editing repo 'rust-lang/infra-smoke-tests':
Branch Protections:
main
Required Checks: ["Run tests", "Check Markdown style", "Check JSON style", "Check Rust style", "Check YAML style", "Lint Markdown files", "Lint Rust code", "Lint YAML files"] => ["Check Markdown style", "Check JSON style", "Check Rust style", "Check YAML style", "Lint Markdown files", "Lint Rust code", "Lint YAML files", "Run tests"]
```
I assume that it's spurious, because it was in the log today, but this repo probably didn't change its protections recently? Another reason why the might be the diff is that the production token cannot update the checks of this repo, but that …
=> Normalize order of branch protection checks

src/github/api/mod.rs, src/github/api/write.rs, src/github/mod.rs, src/github/tests/mod.rs, src/github/tests/test_utils.rs
There was kind of a double empty state for repository descriptions (`None` or `Some("")`), which was causing unnecessary diffs to be displayed in logs (and performed in the API).
Missing or empty description is pretty much the same, and furthermore `team` requires the description field on each repository, so it shouldn't even ever be completely missing anyway (although it might be empty).
This was one of the sources of fake/extra diffs in sync-team dry-run (but also live) output.
=> Change repository description to not be optional

src/github/api/mod.rs
So, https://github.com/rust-lang/sync-team/pull/105 was *almost* right, but what I didn't realize is that even though we now always set the description, there are a few existing repositories without it (and possibly GH can also decide to just return `null` if we set the description to an empty string?).
In any case, this should make the code robust against both scenarios (empty string and `null`), without polluting the codebase with `Option<String>`.
[Dry-run result](https://github.com/rust-lang/sync-team/actions/runs/13716265953/job/38361660346?pr=107)
=> Fix deserialization of repository description

.github/workflows/ci.yml, .github/workflows/run.yml
This should be helpful for moving the actual sync from AWS to GitHub, so that it can be performed in the merge queue directly, and prevent the PR from being merged if it fails. We shouldn't need a conclusion job here, because in CI the deploy part will be simply skipped.
This PR splits the CI workflow into multiple jobs. This allows us to configure the secrets only for the deploy job, and it will also allow us to turn the deploy/sync step into a reusable workflow in the future, to reduce duplication.
A small disadvantage is that the Docker build is now not tested on PRs, but it will be still tested in the merge queue. And we will remove the Docker build once we switch from AWS to GitHub deploy anway.
This will need an infra admin to:
=> Switch CI to use a merge queue

src/github/api/mod.rs, src/github/api/read.rs, src/github/api/tokens.rs, src/github/api/write.rs, src/github/mod.rs, src/github/tests/mod.rs, src/github/tests/test_utils.rs
solves https://github.com/rust-lang/sync-team/issues/121
Discussed in [zulip](https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/sync-team.20dry.20run.20workflow/near/506091368)[#t-infra > sync-team dry run workflow @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/sync-team.20dry.20run.20workflow/near/506091368).
After this change, teams need to request in t-infra to install a GitHub app for them. The `bots` array of the `team` pr won't work anymore.
After this is merged, we can remove the `bots` array from the team repo
=> remove ability to sync GitHub apps

src/github/mod.rs, src/github/tests/mod.rs
This is to avoid the following in the logs:
Me and Jakub prefer this approach wrt https://github.com/rust-lang/sync-team/pull/129
=> ignore noops in diff

src/github/tests/mod.rs, src/github/tests/test_utils.rs
And also track organization membership. This PR only modifies tests.
Should help with https://github.com/rust-lang/sync-team/pull/91.
=> Generalize organization handling in tests
